# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://blog.sadlay.cn
date_format: "ordinal"
title: Sadlay的博客
subtitle: "Focus On Coding Bug >_<"
description: "sadlay's github blog"
keywords: sadlay, lay, layanan
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: sadlay
organization:
organization_url:
github_username: sadlay
location: Beijing, China
email: layanan4ever@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
- href: /
  label: 首页

- href: /categories/
  label: 分类

- href: /wiki/
  label: 维基

- href: /links/
  label: 链接

- href: /about/
  label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
- jekyll-github-metadata
- rouge
#     - jekyll-html-pipeline
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jemoji
#     - jekyll-mentions
collections:
  wiki:
    output: true
    permalink: /wiki/:path/

repository: sadlay/sadlay.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username:
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: sadlay
  repo: sadlay.github.io
  oauth:
    client_id: e2c2d7f4481b3b16f944
    client_secret: d2bdf0f742733e5decf6f99dad05ded44fa18d40
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: sadlay
  repo: sadlay.github.io
  clientID: e2c2d7f4481b3b16f944
  clientSecret: d2bdf0f742733e5decf6f99dad05ded44fa18d40
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
  # 是否支持全文搜索
  fulltext: true
  # 最多显示多少条搜索结果
  limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
  analytics_id: UA-80669434-1
